SELECT P.PRODUCT_ID, P.PRODUCT_NAME,	(P.PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE MONTH(O.PRODUCE_DATE) = '05'
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , PRODUCT_ID ASC