SELECT HISTORY.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND MONTH(HISTORY.START_DATE) = '10'
GROUP BY HISTORY.CAR_ID
ORDER BY HISTORY.CAR_ID DESC