SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, FAVORITES,I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I
INNER JOIN REST_REVIEW R 
ON I.REST_ID = R.REST_ID
WHERE SUBSTRING(I.ADDRESS,1,2) = '서울'
GROUP BY REST_NAME
ORDER BY SCORE DESC,FAVORITES DESC